/*
**control_matrix_command.c
**17-2-2016
**
**
*/

#include "control_matrix_command.h"

static smatrix_command gsmatrix_command_table[] =
{
	{ MATRIX_QUEUE_TYPE, MATRIX_STRING_CMD_QUEUE_TYPE_LEN, MATRIX_STRING_CMD_QUEUE_TYPE },
	{ MATRIX_CHANGE_KEY_PASSWORD, MATRIX_STRING_CMD_CHANGE_KEY_PASSWORD_LEN, MATRIX_STRING_CMD_CHANGE_KEY_PASSWORD },
	{ MATRIX_LOCK_KEYBOARD, MATRIX_STRING_CMD_LOCK_KEYBOARD_LEN, MATRIX_STRING_CMD_LOCK_KEYBOARD },
	{ MATRIX_UNLOCK_KEYBOARD, MATRIX_STRING_CMD_UNLOCK_KEYBOARD_LEN, MATRIX_STRING_CMD_UNLOCK_KEYBOARD },
	{ MATRIX_CLOSE_BELL, MATRIX_STRING_CMD_CLOSE_BELL_LEN, MATRIX_STRING_CMD_CLOSE_BELL },
	{ MATRIX_OPEN_BELL, MATRIX_STRING_CMD_OPEN_BELL_LEN, MATRIX_STRING_CMD_OPEN_BELL },
	{ MATRIX_QUEUE_VERSION, MATRIX_STRING_CMD_QUEUE_VERSION_LEN, MATRIX_STRING_CMD_QUEUE_VERSION },
	{ MATRIX_SET_EXTRON, MATRIX_STRING_CMD_SET_EXTRON_LEN, MATRIX_STRING_CMD_SET_EXTRON },
	{ MATRIX_SET_CREATOR20, MATRIX_STRING_CMD_SET_CREATOR20_LEN, MATRIX_STRING_CMD_SET_CREATOR20 },
	{ MATRIX_CLOSE_SERIAL_RETURN_MSG, MATRIX_STRING_CMD_CLOSE_SERIAL_RETURN_MSG_LEN, MATRIX_STRING_CMD_CLOSE_SERIAL_RETURN_MSG },
	{ MATRIX_OPEN_SERIAL_RETURN_MSG, MATRIX_STRING_CMD_OPEN_SERIAL_RETURN_MSG_LEN, MATRIX_STRING_CMD_OPEN_SERIAL_RETURN_MSG },
	{ MATRIX_SET_LCD_BACKLIGHT_TIME, MATRIX_STRING_CMD_SET_LCD_BACKLIGHT_TIME_LEN, MATRIX_STRING_CMD_SET_LCD_BACKLIGHT_TIME },
	
	{ MATRIX_SET_OUTIN_CORRESPONDING, MATRIX_STRING_CMD_SET_OUTIN_CORRESPONDING_LEN, MATRIX_STRING_CMD_SET_OUTIN_CORRESPONDING },
	{ MATRIX_CLOSE_ALL_OUTPUT_CHANNAL, MATRIX_STRING_CMD_CLOSE_ALL_OUTPUT_CHANNAL_LEN, MATRIX_STRING_CMD_CLOSE_ALL_OUTPUT_CHANNAL },
	{ MATRIX_QUEUE_OUT_CHANNAL_INPUT_STATUS, MATRIX_STRING_CMD_QUEUE_OUT_CHANNAL_INPUT_STATUS_LEN, MATRIX_STRING_CMD_QUEUE_OUT_CHANNAL_INPUT_STATUS },
};

const uint8_t* control_matrix_comand_get( uint16_t cmd_index, uint16_t* p_ascii_cmd_len )
{
	smatrix_command* p_gmatrix_cmd_table = &gsmatrix_command_table[0];
	if( (NULL == p_gmatrix_cmd_table) ||(NULL == p_ascii_cmd_len ) )
		return NULL;

	if( (cmd_index < MATRIX_COMMAND_NUM) && (cmd_index > 0))
	{
		*p_ascii_cmd_len = p_gmatrix_cmd_table[cmd_index].command_len;
		return p_gmatrix_cmd_table[cmd_index].string_command;
	}

	return NULL;
}

